### ISSUE TITLE
Hackintosh USB C Video output

### ISSUE THREAD

**Issue by ltanedo** [vladichimescu/msi-gs65-hackintosh#2]
Hey you mentioned that something about enabling USB c video output.  Does it work in your build? Thanks.

**Comment by ghost** [comment]
@ltanedo this is already answer in the other closed issue, also in the README on the first page: problem: external monitor usb-c not working
fix: in clover GUI, drop table SSDT-DDGPU.aml
do keep in mind that dropping that table will enable your dgpu which will affect battery life
