### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Nemec163** [vladichimescu/msi-gs65-hackintosh#4]
Hi again :)

I'm trying to get HDMI and MDport working to plug monitors. So i've installed High Sierra 10.13.6 based on these repo's:

https://github.com/abc3436645/MSI-GS65-macos-10.13.6
https://github.com/goofysun/MSI-GS65-macOS

All is fine with 630, but system don't see 1060. Tried different settings, Nvidia drivers - nothing.
Any suggestions?

**Comment by ghost** [comment]
@nemec drop or delete the dgpu dsdt to have nvidia and video output enabled if you use my git stuff (I don't have time to check other guys stuff for at least a few months)
