### ISSUE TITLE
Can you help pls

### ISSUE THREAD

**Issue by MaximSavin** [vladichimescu/msi-gs65-hackintosh#5]
Hello, I try to install MacOS Mojave, with your clover kext/settings preset.
I have MSI GS65 Stealth THIN-051 (GTX 1060)

But I have trouble.

If I try to format destination drive in HFS(Journal) — on 2 minutes less, Installation rebooted with error: 
`disk23s1 is not convertible to APFS: You may not install to this volume because it can not be converted to Apple File System (APFS)`
and post installation loop rebooted...

If I try to format destination drive to APFS — sometimes formatting done, but installation reboot without any errors in log, and sometimes formatting not done just rebooted...

Sorry I'm newbie in Hackintosh, I try many options, but not understand what exactly should I do...

Can you please explain step by step installation process, please?

Thanx a lot if you can help!

**Comment by ghost** [comment]
hi Savin.
sorry, I do not provide install support as it's not related to the actual files - most probably you need to delete the entire volume and recreate the partition using GUID GPT. other than the 'normal' install procedure, copy>paste everything related to clover from here should be enough

**Comment by MaximSavin** [comment]
omg, maybe it should help, I try to install on the second drive within windows 10...

Thanx, I'll try, but simple question: for Mojave should I format destination drive to APFS or HFS (in different guides different information)?

**Comment by ghost** [comment]
they recommend to alway use the latest thing which is APFS. each format needs the specific efi driver so clover can read the partition
