### ISSUE TITLE
Version of Mac OS for this mackintosh

### ISSUE THREAD

**Issue by ltanedo** [vladichimescu/msi-gs65-hackintosh#6]
Hey vladichimescu, 

     What version of Mac OS was used for this mackintosh? Was it 10.14.3? Thanks!

**Comment by ghost** [comment]
this is not a issue so please don't create one just to ask questions - there is a "last updated" date in the readme based on which you can find the latest available version on that date. also, any 10.4.x should work, the problem is with your install, not with the files
