### ISSUE TITLE
Bluetooth not working after BCM94352Z wifi card replacement

### ISSUE THREAD

**Issue by lloyd-tanedo** [vladichimescu/msi-gs65-hackintosh#7]
All three kexts are already in the clover/kexts/other 
AirportBrcmFixup.kext
BrcmFirmwareRepo.kext
BrcmPatchRAM2.kext

also tried putting the three kexts in S/L/E rebuilding the kextcache

Bluetooth still isn't working.  Is it working on your machine vladichimescu? Thanks!

**Comment by ghost** [comment]
please read the README. those kext are for the replaced wifi/bt combo card. the original card is a no go

**Comment by lloyd-tanedo** [comment]
I did read your guide and replaced the original card with the BCM94352Z.  Wifi is working but bluetooth isn't.  I've read online that installing the three kexts to /L/E fixes the issues, but its not working for me.  Any ideas?

**Comment by ghost** [comment]
check the bt device id and copy the firmware from Windows or Rehabman repo to BrcmFirmwareRepo
