### ISSUE TITLE
Laptop switching to dgpu after wake from sleep

### ISSUE THREAD

**Issue by lloyd-tanedo** [vladichimescu/msi-gs65-hackintosh#8]
After waking up from sleep, the light next to the power button is orange indicating that the dgpu is on (white when the igpu is on).  Battery Life after this is greatly reduced leading me to believe that the dgpu is indeed on.  

While this could be a bug where the indicator light just turns orange, but I don't think so as this light is probably hardcoded into the hardware and bios.

**Comment by ghost** [comment]
The ioreg does not pick it up but based on my investigation it's powered on. What you can do is to power the dgpu before sleep and power it off after wake in the dsdt.
I can no longer suport the device as I no longer own one so you will have to try it yourself (rehabman has instructions for it already posted)

**Comment by lloyd-tanedo** [comment]
Ok I'll give it a shot.  Thanks for making the guide for us!

**Comment by tmtd2** [comment]
what Mac OS does this config work with?
